### PR TITLE
Tag latest ensembler

### PR DESCRIPTION
**Pull request by ashwinath**
Right now it does not have the latest tag with each new release. This PR adds the latest tag so that we can always pull the latest for testing purposes.

### CODE REVIEW

**Comment by romanwozniak** [comment]
Using `latest` tag is an anti-pattern for most of scenarios. It kills the reproducibility of the deployment as well as introduces some hard-to-discover side effects (i.e. if deployed with kubernetes and `imagePullPolicy` is set to `IfNotPresent`, then the resulting deployment might be not what you expect it to be).

**Comment by ashwinath** [comment]
> Using `latest` tag is an anti-pattern for most of scenarios. It kills the reproducibility of the deployment as well as introduces some hard-to-discover side effects (i.e. if deployed with kubernetes and `imagePullPolicy` is set to `IfNotPresent`, then the resulting deployment might be not what you expect it to be).

I agree with you on this, if you set the `latest` tag in your deployments the developer ought to be slapped. But I dont think that's the use case for this latest tag. It's good for stuff like integration tests, or if someone wants to play around with the container without having to lookup the commit hash they need for the latest part.

But if you feel strongly about not supporting the latest tags, I'll just close the MR.

**Comment by romanwozniak** [comment]
> > Using `latest` tag is an anti-pattern for most of scenarios. It kills the reproducibility of the deployment as well as introduces some hard-to-discover side effects (i.e. if deployed with kubernetes and `imagePullPolicy` is set to `IfNotPresent`, then the resulting deployment might be not what you expect it to be).
> 
> I agree with you on this, if you set the `latest` tag in your deployments the developer ought to be slapped. But I dont think that's the use case for this latest tag. It's good for stuff like integration tests, or if someone wants to play around with the container without having to lookup the commit hash they need for the latest part.
> 
> But if you feel strongly about not supporting the latest tags, I'll just close the MR.

I'm not completely agains `latest` tag, but:
a) It should only be added to stable releases, not dev builds
b) It should not be used in e2e tests for the reproducibility reasons I described above

This MR doesn't seem to be complaint with these criteria

**Comment by ashwinath** [comment]
> 
> 
> > > Using `latest` tag is an anti-pattern for most of scenarios. It kills the reproducibility of the deployment as well as introduces some hard-to-discover side effects (i.e. if deployed with kubernetes and `imagePullPolicy` is set to `IfNotPresent`, then the resulting deployment might be not what you expect it to be).
> > 
> > 
> > I agree with you on this, if you set the `latest` tag in your deployments the developer ought to be slapped. But I dont think that's the use case for this latest tag. It's good for stuff like integration tests, or if someone wants to play around with the container without having to lookup the commit hash they need for the latest part.
> > But if you feel strongly about not supporting the latest tags, I'll just close the MR.
> 
> I'm not completely agains `latest` tag, but:
> a) It should only be added to stable releases, not dev builds
> b) It should not be used in e2e tests for the reproducibility reasons I described above
> 
> This MR doesn't seem to be complaint with these criteria

Actually on second thoughts, it's not good on integration tests.

Okay it makes sense, it should be on tags. Closing this PR.

**Pull request closed without merging**
